-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Layouts

-- ----------------------------------------------------- 

hl.config({
    dwindle = {
        --    pseudotile = true
        preserve_split = true,
    },
})

hl.config({
    master = {
        -- Commented out due to compatibility reasons
        -- new_status = master
    },
})

--gestures {

--    workspace_swipe = false

--}
