# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule {
  name = windowrule-1
  tile = on
  match:class = ^(Microsoft-edge)$
}

windowrule {
  name = brave
  tile = on
  match:class = ^(Brave-browser)$
}

windowrule {
  name = chromium
  tile = on
  match:class = ^(Chromium)$
}

windowrule {
  name = pavucontrol
  float = on
  match:class = ^(pavucontrol)$
}

windowrule {
  name = windowrule-5
  float = on
  match:class = ^(blueman-manager)$
}

windowrule {
  name = windowrule-6
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = windowrule-7
  float = on
  match:class = ^(qalculate-gtk)$
}


# Browser Picture in Picture
windowrule {
  name = picture-in-picture
  float = on
  pin = on
  move = ((monitor_w*0.695)) ((monitor_h*0.04))
  match:title = ^(Picture-in-Picture)$
}


# Cava background
windowrule {
  name = cava
  monitor = DP-1
  match:class = ^(alacritty-cava-bg)$
}

