-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Window rules

-- ----------------------------------------------------- 

hl.window_rule({
    name  = "windowrule-1",
    match = {
        class = "^(Microsoft-edge)$",
    },
    tile = true,
})

hl.window_rule({
    name  = "brave",
    match = {
        class = "^(Brave-browser)$",
    },
    tile = true,
})

hl.window_rule({
    name  = "chromium",
    match = {
        class = "^(Chromium)$",
    },
    tile = true,
})

hl.window_rule({
    name  = "pavucontrol",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        class = "^(qalculate-gtk)$",
    },
    float = true,
})

-- Browser Picture in Picture

hl.window_rule({
    name  = "picture-in-picture",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    pin = true,
    move = { "((monitor_w*0.695))", "((monitor_h*0.04))" },
})

-- Cava background

hl.window_rule({
    name  = "cava",
    match = {
        class = "^(alacritty-cava-bg)$",
    },
    monitor = "DP-1",
})
