-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Animations

-- name "Fast"

-- ----------------------------------------------------- 

hl.config({
    animations = {
        enabled = true,
    },
})

-- Restored by hand: hyprconf2lua silently dropped every bezier/animation line.
-- NB: "linear" here redefines one of Hyprland's built-in curves. Same control
-- points as the built-in, so it's a no-op either way, but that's where to look
-- if this variation ever complains about a duplicate curve name.

hl.curve("linear",        { type = "bezier", points = { { 0, 0 },      { 1, 1 } } })
hl.curve("md3_standard",  { type = "bezier", points = { { 0.2, 0 },    { 0, 1 } } })
hl.curve("md3_decel",     { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel",     { type = "bezier", points = { { 0.3, 0 },    { 0.8, 0.15 } } })
hl.curve("overshot",      { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("crazyshot",     { type = "bezier", points = { { 0.1, 1.5 },  { 0.76, 0.92 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("fluent_decel",  { type = "bezier", points = { { 0.1, 1 },    { 0, 1 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.85, 0 },   { 0.15, 1 } } })
hl.curve("easeOutCirc",   { type = "bezier", points = { { 0, 0.55 },   { 0.45, 1 } } })
hl.curve("easeOutExpo",   { type = "bezier", points = { { 0.16, 1 },   { 0.3, 1 } } })

hl.animation({ leaf = "windows",          enabled = true, speed = 3,   bezier = "md3_decel",   style = "popin 60%" })
hl.animation({ leaf = "border",           enabled = true, speed = 10,  bezier = "default" })
hl.animation({ leaf = "fade",             enabled = true, speed = 2.5, bezier = "md3_decel" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 3.5, bezier = "easeOutExpo", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3,   bezier = "md3_decel",   style = "slidevert" })
