-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Animations

-- name "Default"

-- ----------------------------------------------------- 

hl.config({
    animations = {
        enabled = true,
    },
})

-- hyprconf2lua dropped every `bezier =` and `animation =` line from the .conf
-- without flagging it, which left this file as just `enabled = true` -- i.e.
-- Hyprland's stock animations. Restored by hand from conf/animations/default.conf.
--
-- `bezier = NAME, x1, y1, x2, y2`            -> hl.curve(NAME, { type = "bezier", points = {{x1,y1},{x2,y2}} })
-- `animation = LEAF, ON, SPEED, CURVE[, STYLE]` -> hl.animation({ leaf, enabled, speed, bezier[, style] })

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",     enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 7,  bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",      enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",        enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 6,  bezier = "default" })
