-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("conf.colors")

-- ----------------------------------------------------- 

-- General window layout and colors

-- name: "Default"

-- ----------------------------------------------------- 

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 14,
        border_size = 1,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = "rgba(ffffffff)",
            inactive_border = colors.color11,
        },
    },
})
