-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("conf.colors")

-- ----------------------------------------------------- 

-- General window layout and colors

-- name: "No Border More Gaps"

-- ----------------------------------------------------- 

hl.config({
    general = {
        gaps_in = 20,
        gaps_out = 40,
        border_size = 0,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = colors.color11,
            inactive_border = "rgba(ffffffff)",
        },
    },
})
