-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- General window decoration

-- name: "Default"

-- ----------------------------------------------------- 

-- rounding and inactive_opacity used to be overwritten a few seconds into every
-- reload by ~/.config/ml4w-hyprland-settings/hyprctl.sh, which replayed whatever
-- the ML4W Hyprland Settings app had last written to its own hyprctl.json. The
-- values it was applying (7 and 1.0) are now simply the values here, and that
-- script, its JSON and the app that wrote them are gone -- so what this file
-- says is what you get.
hl.config({
    decoration = {
        rounding = 7,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            -- blurls = waybar
        },
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
        shadow = {
            range = 30,
            render_power = 3,
            color = "0x66000000",
        },
        --    drop_shadow = true
        --    shadow_range = 30
        --    shadow_render_power = 3
        --    col.shadow = 0x66000000
    },
})
