-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- General window decoration

-- name: "No Rounding"

-- ----------------------------------------------------- 

hl.config({
    decoration = {
        rounding = 0,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            -- blurls = quickshell
        },
        active_opacity = 1.0,
        inactive_opacity = 0.8,
        fullscreen_opacity = 1.0,
        drop_shadow = true,
        shadow_range = 30,
        shadow_render_power = 3,
        col = {
            shadow = "0x66000000",
        },
    },
})
