-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- General window decoration

-- name: "Rounding All Blur No Shadows"

-- ----------------------------------------------------- 

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 12,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            blurls = "quickshell",
        },
        active_opacity = 0.9,
        inactive_opacity = 0.6,
        fullscreen_opacity = 0.9,
        drop_shadow = false,
        shadow_range = 30,
        shadow_render_power = 3,
        col = {
            shadow = "0x66000000",
        },
    },
})
