-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- General window decoration

-- name: "Rounding More Blur"

-- ----------------------------------------------------- 

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 12,
            passes = 6,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            -- blurls = waybar
        },
        active_opacity = 1.0,
        inactive_opacity = 0.6,
        fullscreen_opacity = 1.0,
        drop_shadow = true,
        shadow_range = 30,
        shadow_render_power = 3,
        col = {
            shadow = "0x66000000",
        },
    },
})
