# Preload Wallpapers
preload = /home/omar/wallpaper/headphones-paint-color-splash.jpg

# Set Wallpapers
wallpaper = ,/home/omar/wallpaper/headphones-paint-color-splash.jpg

# Disable Splash
splash = false
