-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Autostart

-- ----------------------------------------------------- 

-- Setup XDG for screen sharing

--exec-once = ~/.config/hypr/scripts/xdg.sh

-- Start Polkit

-- Test Polkit pkexec --user username alacritty


-- Load Dunst Notification Manager


-- Load GTK settings


-- Using hypridle to start hyprlock


-- Load cliphist history


-- Autostart ML4W App


-- Start ewww daemon


-- Initialize waypaper

-- exec-once = waypaper --restore


-- Launch Waybar


-- Start autostart cleanup


-- Load configuration from ML4W Hyprland Settings App


-- reload plugins


-- autostart cava


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dunst")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    -- Dropped: the ML4W welcome autostart (disabled by a cache marker for years,
    -- and it referenced the postinstall script we removed), and `ags &` -- that
    -- config was ML4W's v1 sidebar, which the installed v3 (Astal) could not
    -- read; both the config and the whole AGS/Astal package stack are now gone.
    -- Waybar is the bar in use.
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("~/.config/hypr/scripts/cleanup.sh")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("~/.config/hypr/scripts/manage-cava.sh")
end)

-- Nothing runs on reload any more. What used to live here was the ML4W Hyprland
-- Settings app's hyprctl.sh, which slept three seconds and then reapplied its
-- own hyprctl.json over the top of this config -- so the file you edited was not
-- the last word on decoration:rounding or decoration:inactive_opacity. Those two
-- values now live in conf/decorations/default.lua, and the script, its JSON and
-- the AppImage that generated them have been removed.
