-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Autostart

-- ----------------------------------------------------- 

-- Setup XDG for screen sharing

--exec-once = ~/.config/hypr/scripts/xdg.sh

-- Start Polkit

-- Test Polkit pkexec --user username alacritty


-- Load Dunst Notification Manager


-- Load GTK settings


-- Using hypridle to start hyprlock


-- Load cliphist history


-- Autostart ML4W App


-- Start ewww daemon


-- Initialize waypaper

-- exec-once = waypaper --restore


-- Launch Waybar


-- Start autostart cleanup


-- Load configuration from ML4W Hyprland Settings App


-- reload plugins


-- autostart cava


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dunst")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    -- Dropped: the ML4W welcome autostart (disabled by a cache marker for years,
    -- and it referenced the postinstall script we removed), and `ags &` -- the
    -- installed ags is v3 (Astal) while ~/.config/ags was a v1 config, so bare
    -- `ags` just printed its help and exited. Waybar is the bar in use.
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("~/.config/hypr/scripts/cleanup.sh")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("~/.config/hypr/scripts/manage-cava.sh")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/ml4w-hyprland-settings/hyprctl.sh")
end)
