-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Add your additional Hyprland configurations here

-- 

-- This is an additional key binding 

-- bind = $mainMod CTRL, up, workspace, empty

-- 

-- Example for xwayland

-- xwayland {

--   force_zero_scaling = true

-- }

-- SDL version

hl.env("SDL_VIDEODRIVER", "wayland")

-- env = SDL_VIDEODRIVER,x11

-- Cava desktop background, via hyprwinwrap.
--
-- The original hyprwm hyprwinwrap is gone -- it's no longer in the
-- hyprland-plugins repo, so this was dead config even before the Lua move.
-- Maintained fork, needs Hyprland 0.54+ (we're on 0.56.2):
--     hyprpm add https://github.com/gen3vra/hyprwinwrap
--     hyprpm enable hyprwinwrap
--
-- The fork is Lua-native: rather than `plugin:hyprwinwrap:class` config keys it
-- registers a function, hl.plugin.hyprwinwrap.window(). That function only
-- exists once the plugin is loaded, and `hyprpm reload` in conf/autostart.lua
-- runs *after* this file is parsed -- so the nil guard is required, not
-- decorative. Without the plugin installed this block is simply skipped.
--
-- NB: class is an EXACT match now, NOT a regex. "alacritty-cava-bg" is the
-- --class passed by scripts/manage-cava.sh.
if hl.plugin.hyprwinwrap ~= nil then
    hl.plugin.hyprwinwrap.window({
        class  = "alacritty-cava-bg",
        layer  = 0,
        -- Percentages of the screen. size_y = 97 would leave a strip for the bar.
        pos_x  = 0,
        pos_y  = 0,
        size_x = 100,
        size_y = 100,
    })
end

hl.window_rule({
    name  = "alacritty",
    match = {
        class = "^(Alacritty)$",
    },
    no_blur = true,
})
