-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Keyboard Layout

-- https://wiki.hyprland.org/Configuring/Variables/#input

-- -----------------------------------------------------

hl.config({
    input = {
        kb_layout = "gb",
        numlock_by_default = true,
        mouse_refocus = false,
        -- For United States
        -- kb_layout = us
        -- kb_variant = intl
        -- kb_model = pc105
        -- kb_options =
        follow_mouse = 1,
        touchpad = {
            -- for desktop
            natural_scroll = false,
            -- for laptop
            -- natural_scroll = yes
            -- middle_button_emulation = true
            -- clickfinger_behavior = false          
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

--gestures {

--    workspace_swipe = true

--}
