-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- ML4W configurations

-- ----------------------------------------------------- 

-- Pavucontrol floating

hl.window_rule({
    name  = "windowrule-1",
    match = {
        class = "(.*org.pulseaudio.pavucontrol.*)",
    },
    float = true,
    size = { 700, 600 },
    center = true,
    pin = true,
})

-- OpenAI ChatGPT floating

hl.window_rule({
    name  = "windowrule-2",
    match = {
        title = "(ChatGPT.*)",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-3",
    match = {
        title = "(.*chat.openai.com.*)",
    },
    float = true,
    size = { 500, "(monitor_h*0.5)" },
    move = { "(20)", "(70)" },
})

-- Dropped: a float/centre/pin rule for waypaper's window. The wallpaper chooser
-- is a Quickshell layer surface now, so there is no toplevel for a window rule
-- to match, and the package is uninstalled.

-- ML4W Welcome App floating

hl.window_rule({
    name  = "windowrule-5",
    match = {
        class = "(com.ml4w.welcome)",
    },
    float = true,
    size = { 700, 600 },
    center = true,
    pin = true,
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        class = "(ml4w-welcome.py)",
    },
    float = true,
    size = { 400, 500 },
    center = true,
    pin = true,
})

-- ML4W Settings App floating

hl.window_rule({
    name  = "windowrule-7",
    match = {
        class = "(com.ml4w.dotfilessettings)",
    },
    float = true,
    size = { 700, 600 },
    move = { "((monitor_w*0.1))", "((monitor_h*0.2))" },
    pin = true,
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        class = "(ml4w-dotfiles-settings.py)",
    },
    float = true,
    size = { 400, 500 },
    move = { "((monitor_w*0.1))", "((monitor_h*0.2))" },
    pin = true,
})

-- The two float rules for the ML4W Hyprland Settings app (com.ml4w.hyprland.settings
-- and ml4w-hyprland-settings.py) were removed with the app itself: it wrote a
-- hyprctl.json that got replayed over this config on every reload. See
-- conf/decorations/default.lua for the two settings it used to impose.

-- System Mission Center

hl.window_rule({
    name  = "windowrule-11",
    match = {
        class = "(io.missioncenter.MissionCenter)",
    },
    float = true,
    pin = true,
    center = true,
    size = { 900, 600 },
})

-- System Mission Center Preference Window

hl.window_rule({
    name  = "windowrule-12",
    match = {
        class = "(missioncenter)",
        title = "^(Preferences)$",
    },
    float = true,
    pin = true,
    center = true,
})

-- Gnome Calculator

hl.window_rule({
    name  = "windowrule-13",
    match = {
        class = "(org.gnome.Calculator)",
    },
    float = true,
    size = { 700, 600 },
    center = true,
})

-- Emoji Picker Smile

hl.window_rule({
    name  = "windowrule-14",
    match = {
        class = "(it.mijorus.smile)",
    },
    float = true,
    pin = true,
    move = { "((monitor_w*1)-window_w-40)", "(90)" },
})

-- Hyprland Share Picker

hl.window_rule({
    name  = "windowrule-15",
    match = {
        class = "(hyprland-share-picker)",
    },
    float = true,
    pin = true,
    size = { 600, 400 },
})

hl.window_rule({
    name  = "windowrule-16",
    match = {
        title = "class:(hyprland-share-picker)",
    },
    center = true,
})

-- General floating

hl.window_rule({
    name  = "windowrule-17",
    match = {
        class = "(dotfiles-floating)",
    },
    float = true,
    size = { 1000, 700 },
    center = true,
    pin = true,
})

-- XDG Desktop Portal

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- QT

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- GDK

hl.env("GDK_SCALE", 1)

-- Toolkit Backend

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("CLUTTER_BACKEND", "wayland")

-- Mozilla

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- Set the cursor size for xcursor

hl.env("XCURSOR_SIZE", 24)

-- Disable appimage launcher by default

hl.env("APPIMAGELAUNCHER_DISABLE", 1)

-- Ozone

hl.env("OZONE_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
