# ----------------------------------------------------- 
# ML4W configurations
# ----------------------------------------------------- 

# Pavucontrol floating
windowrule {
  name = windowrule-1
  float = on
  size = 700 600
  center = on
  pin = on
  match:class = (.*org.pulseaudio.pavucontrol.*)
}


# OpenAI ChatGPT floating
windowrule {
  name = windowrule-2
  float = on
  match:title = (ChatGPT.*)
}

windowrule {
  name = windowrule-3
  float = on
  size = 500 (monitor_h*0.5)
  move = (20) (70)
  match:title = (.*chat.openai.com.*)
}


# ML4W Welcome App floating
windowrule {
  name = windowrule-4
  float = on
  size = 800 700
  center = on
  pin = on
  match:class = (.*waypaper.*)
}


# ML4W Welcome App floating
windowrule {
  name = windowrule-5
  float = on
  size = 700 600
  center = on
  pin = on
  match:class = (com.ml4w.welcome)
}


windowrule {
  name = windowrule-6
  float = on
  size = 400 500
  center = on
  pin = on
  match:class = (ml4w-welcome.py)
}


# ML4W Settings App floating
windowrule {
  name = windowrule-7
  float = on
  size = 700 600
  move = ((monitor_w*0.1)) ((monitor_h*0.2))
  pin = on
  match:class = (com.ml4w.dotfilessettings)
}


windowrule {
  name = windowrule-8
  float = on
  size = 400 500
  move = ((monitor_w*0.1)) ((monitor_h*0.2))
  pin = on
  match:class = (ml4w-dotfiles-settings.py)
}


# ML4W Hyprland App floating
windowrule {
  name = windowrule-9
  float = on
  size = 700 600
  center = on
  pin = on
  match:class = (com.ml4w.hyprland.settings)
}


windowrule {
  name = windowrule-10
  float = on
  size = 700 600
  center = on
  pin = on
  match:class = (ml4w-hyprland-settings.py)
}


# System Mission Center
windowrule {
  name = windowrule-11
  float = on
  pin = on
  center = on
  size = 900 600
  match:class = (io.missioncenter.MissionCenter)
}


# System Mission Center Preference Window
windowrule {
  name = windowrule-12
  float = on
  pin = on
  center = on
  match:class = (missioncenter)
  match:title = ^(Preferences)$
}


# Gnome Calculator
windowrule {
  name = windowrule-13
  float = on
  size = 700 600
  center = on
  match:class = (org.gnome.Calculator)
}


# Emoji Picker Smile
windowrule {
  name = windowrule-14
  float = on
  pin = on
  move = ((monitor_w*1)-window_w-40) (90)
  match:class = (it.mijorus.smile)
}


# Hyprland Share Picker
windowrule {
  name = windowrule-15
  float = on
  pin = on
  size = 600 400
  match:class = (hyprland-share-picker)
}

windowrule {
  name = windowrule-16
  center = on
  match:title = class:(hyprland-share-picker)
}


# General floating
windowrule {
  name = windowrule-17
  float = on
  size = 1000 700
  center = on
  pin = on
  match:class = (dotfiles-floating)
}


# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
