-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- NB: the generator emitted `conf.windows.border_1`, which resolves to
-- conf/windows/border_1.lua and does not exist. require() only rewrites `.` to
-- `/`, so the hyphen in the real filename has to be kept.
require("conf.windows.border-1")
