-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Environment Variables

-- name: "Default"

-- ----------------------------------------------------- 

-- The hardware overlay for this machine (AMD/Intel, nothing special needed), so
-- it is deliberately empty. The shared variables live in base.lua, which
-- conf/environment.lua requires alongside this file.
