-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Environment Variables

-- name: "Default"

-- ----------------------------------------------------- 

-- Default Settings in ml4w.conf
