-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Environment Variables

-- name: "KVM"

-- ----------------------------------------------------- 

-- Default Settings in ml4w.conf

-- KVM Environment

hl.env("WLR_RENDERER_ALLOW_SOFTWARE", 1)

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})
