-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Environment Variables

-- name: "Nvidia"

-- ----------------------------------------------------- 

-- Default Settings in ml4w.conf

-- NVIDIA https://wiki.hyprland.org/Nvidia/

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

-- env = __GL_VRR_ALLOWED,1

-- env = WLR_DRM_NO_ATOMIC,1

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})
