-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Monitor Setup

-- name: "1366x768"

-- ----------------------------------------------------- 

hl.monitor({
    output   = "",
    mode     = "1366x768",
    position = "auto",
    scale    = 1,
})
