-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Monitor Setup

-- name: "3440x1440"

-- ----------------------------------------------------- 

hl.monitor({
    output   = "",
    mode     = "3440x1440",
    position = "auto",
    scale    = 1,
})
