-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "DP-1",
    mode     = "3440x1440 highrr",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-3",
    mode     = "3840x2160",
    position = "3440x0",
    scale    = 2,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "3840x2160",
    position = "-1920x0",
    scale    = 2,
})
